<?php

/**
 * Example: Creating a custom queue storage backend.
 *
 * The QueueStorage interface defines how jobs are persisted.
 * By implementing it, you can store jobs anywhere:
 * - In-memory (for testing)
 * - Database (for multi-server deployments)
 * - Redis (for high-throughput)
 * - Any other backend
 *
 * The Queue class handles serialization, encryption, and retry logic.
 * The storage only needs to store and retrieve raw strings.
 */
require_once __DIR__.'/../vendor/autoload.php';

use WebFiori\Queue\Job;
use WebFiori\Queue\Queue;
use WebFiori\Queue\QueueStorage;

/**
 * An in-memory queue storage implementation.
 *
 * Jobs are stored in PHP arrays and lost when the process ends.
 * This is useful for:
 * - Unit testing (no file system or database needed)
 * - Short-lived CLI scripts where persistence isn't needed
 * - Understanding how the QueueStorage interface works
 */
class InMemoryQueueStorage implements QueueStorage {
    /** @var array Pending jobs indexed by ID */
    private array $pending = [];

    /** @var array Failed jobs indexed by ID */
    private array $failed = [];

    /**
     * Store a job in the pending queue.
     *
     * @param string $id Unique identifier for the job (generated by Queue::dispatch)
     * @param string $payload The serialized (and possibly encrypted) job data.
     *                        The storage should treat this as an opaque string.
     * @param int $priority Higher number = processed first. Default is 0.
     * @param int $availableAt Unix timestamp when the job becomes available.
     *                         Jobs with availableAt in the future are skipped by pop().
     */
    public function push(string $id, string $payload, int $priority = 0, int $availableAt = 0): void {
        $this->pending[$id] = [
            'id' => $id,
            'payload' => $payload,
            'priority' => $priority,
            'attempts' => 0,
            'available_at' => $availableAt > 0 ? $availableAt : time(),
        ];
    }

    /**
     * Retrieve the next available jobs from the queue.
     *
     * Must return jobs that:
     * 1. Have available_at <= current time (not delayed)
     * 2. Are sorted by priority (highest first)
     * 3. Are limited to $limit count
     *
     * @param int $limit Maximum number of jobs to return.
     * @return array Each element is an associative array with keys:
     *               id, payload, priority, attempts, available_at
     */
    public function pop(int $limit = 10): array {
        // Filter: only jobs whose available_at has passed
        $available = array_filter($this->pending, fn ($j) => $j['available_at'] <= time());

        // Sort: highest priority first
        usort($available, fn ($a, $b) => $b['priority'] - $a['priority']);

        // Limit: return at most $limit jobs
        return array_slice($available, 0, $limit);
    }

    /**
     * Remove a completed job from the pending queue.
     * Called by Queue::process() after handle() succeeds.
     *
     * @param string $id The job identifier.
     */
    public function markComplete(string $id): void {
        unset($this->pending[$id]);
    }

    /**
     * Move a job from pending to failed.
     * Called by Queue::process() when all retry attempts are exhausted.
     *
     * @param string $id The job identifier.
     * @param string $reason The exception message from the last failed attempt.
     * @param int $attempts Total number of attempts made.
     */
    public function markFailed(string $id, string $reason, int $attempts): void {
        $data = $this->pending[$id] ?? [];
        unset($this->pending[$id]);
        $data['reason'] = $reason;
        $data['attempts'] = $attempts;
        $this->failed[$id] = $data;
    }

    /**
     * Update the attempt count for a pending job.
     * Called by Queue::process() before re-queuing a failed job for retry.
     *
     * @param string $id The job identifier.
     * @param int $attempts The updated attempt count.
     */
    public function setAttempts(string $id, int $attempts): void {
        if (isset($this->pending[$id])) {
            $this->pending[$id]['attempts'] = $attempts;
        }
    }

    /**
     * Move a failed job back to the pending queue for reprocessing.
     * Called by Queue::retry() when a developer wants to retry a failed job.
     *
     * @param string $id The job identifier.
     */
    public function retry(string $id): void {
        if (isset($this->failed[$id])) {
            $data = $this->failed[$id];
            unset($this->failed[$id], $data['reason']);
            $data['available_at'] = time();
            $this->pending[$id] = $data;
        }
    }

    /**
     * Returns the number of jobs waiting to be processed.
     *
     * @return int
     */
    public function getPendingCount(): int {
        return count($this->pending);
    }

    /**
     * Returns all failed jobs for inspection.
     *
     * @return array Each element has: id, payload, reason, attempts
     */
    public function getFailed(): array {
        return array_values($this->failed);
    }

    /**
     * Remove all failed jobs permanently.
     * Called by Queue::flush() to clear the dead letter queue.
     */
    public function flush(): void {
        $this->failed = [];
    }
}

// --- Usage ---

/**
 * A simple job that prints a message.
 */
class PrintJob implements Job {
    public function __construct(private string $message) {
    }

    public function handle(): void {
        echo "Processing: {$this->message}\n";
    }

    public function getMaxAttempts(): int {
        return 3;
    }

    public function getRetryDelaySeconds(): int {
        return 5;
    }
}

// Create a queue using our custom in-memory storage.
// In production, you'd pass a DatabaseQueueStorage or RedisQueueStorage here.
$queue = new Queue(new InMemoryQueueStorage());

// Dispatch jobs with different priorities.
// The queue stores them but does NOT execute them yet.
$queue->dispatch(new PrintJob('First task'));
$queue->dispatch(new PrintJob('High priority task'), priority: 10);
$queue->dispatch(new PrintJob('Normal task'));

echo "Pending: ".$queue->getPendingCount()."\n\n";

// Process all pending jobs.
// They execute in priority order: high priority first.
$processed = $queue->process();
echo "\nProcessed: $processed jobs\n";
echo "Remaining: ".$queue->getPendingCount()."\n";
